Updated some values

diff --git a/mongo/templates/mongodb-setup-scripts.yaml b/mongo/templates/mongodb-setup-scripts.yaml
--- a/mongo/templates/mongodb-setup-scripts.yaml
+++ b/mongo/templates/mongodb-setup-scripts.yaml
@@ -17,18 +17,29 @@ data:
     }
 
     echo "Waiting for mongodb to come up"
-    until mongo --host {{ template "name" . }}.{{ .Release.Namespace }} --port 27017 --eval "db.adminCommand('ping')" > /dev/null 2>&1; do
-    echo "Waiting for db availability"
-    sleep 5
+
+    until mongo --host {{ template "name" . }}.{{ .Release.Namespace }} --port 27017 --eval "db.adminCommand('ping')" > /dev/null 2>&1; 
+    do
+      echo "Waiting for db availability"
+      sleep 2
     done
+
     echo "DB ready. Configuring..."
-    mongo --host {{ template "name" . }}.{{ .Release.Namespace }} --port 27017 < /scripts/createMongoDBUsers.js || errorExit "DB user setup failed"
+    
+    #mongo --host {{ template "name" . }}.{{ .Release.Namespace }} --port 27017 < /scripts/createMongoDBUsers.js || errorExit "DB user setup failed"
+    until mongo --host {{ template "name" . }}.{{ .Release.Namespace }} --port 27017 < /scripts/createMongoDBUsers.js ; 
+    do
+      echo "Waiting for executing user creation command on master node"
+      sleep 2
+    done
+
     echo "DB config done"
+
 
   createMongoDBUsers.js: |
     // Problem - Request was going to random node from cluster and sometime it was failing on slave node.
     // Solution - execute this command on admin host only
-    rs.initiate()
+    // rs.initiate()
 
     // Creating default admin user
     var adminUser = {
